version: "3"
services:
  hub:
    image: selenium/hub:3.14
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  searchmodule:
      image: dragandragan04/docker-selenium-testng
      depends_on:
        - chrome
      environment:
        - BROWSER=chrome
        - HUB_HOST=hub
        - MODULE=search-module.xml
      volumes:
        - ./search-result-chrome:/usr/share/udemy/test-output
  searchmodule:
      image: dragandragan04/docker-selenium-testng
      depends_on:
        - firefox
      environment:
        - BROWSER=firefox
        - HUB_HOST=hub
        - MODULE=search-module.xml
      volumes:
        - ./search-result-firefox:/usr/share/udemy/test-output
  book-flight-module:
      image: dragandragan04/docker-selenium-testng
      depends_on:
        - chrome
        - firefox
      environment:
        - BROWSER=chrome
        - HUB_HOST=hub
        - MODULE=book-flight-module.xml
      volumes:
        - ./book-result-chrome:/usr/share/udemy/test-output
  book-flight-module:
      image: dragandragan04/docker-selenium-testng
      depends_on:
        - chrome
      environment:
        - BROWSER=firefox
        - HUB_HOST=hub
        - MODULE=book-flight-module.xml
      volumes:
        - ./book-result-firefox:/usr/share/udemy/test-output      